seed: 2023

fake_subscribers:
    num_subs: 100
    min_age: 18 # legal age in ph, just a heuristic
    max_age: 72 # life expectancy in ph ao 2022

fake_cellsites:
    gadm_version: 4.0 # see https://gadm.org/data.html
    sample_frac: 0.5 # how much to keep from init node count
    min_distance: 300 # this is haversine distance in meters
    town_keyword: Taguig

fake_transactions:
    k_nearest_neighbor: 5 # controls "random-ness" of hop simulation
