# you can configure the parameters to generate fake data below 
# https://hydra.cc/docs/tutorials/basic/your_first_app/simple_cli/

seed: 2023

fake_subscribers:
    filepath_subscribers: data/fake_subscribers.csv
    num_subs: 100
    min_age: 18 # legal age in ph, just a heuristic
    max_age: 72 # life expectancy in ph ao 2022

fake_cellsites:
    filepath_cellsites: data/fake_cellsites.csv
    filepath_cellsites_picture: docs/fake_cellsites.png
    ad_level: 2
    gadm_version: 4.0 # see https://gadm.org/data.html
    sample_frac: 0.5 # how much to keep from init node count
    min_distance: 300 # this is haversine distance in meters
    town_keyword: Taguig

fake_transactions:
    filepath_transactions: data/fake_transactions.csv
    # two params below controls the "random-ness" of hop simulation
    k_nearest_neighbor: 3
    start_date: '2023-06-01'
    num_days: 30
    # https://www.dailymail.co.uk/sciencetech/article-3042230/Sleeping-habits-world-revealed-wakes-grumpy-China-best-quality-shut-eye-South-Africa-wakes-earliest.html
    cap_start_hr: 7 # controls the start hour of sub in a day
